name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Download ipa file
        run: |
          ./download
      - name: Fastlane Action
        uses: maierj/fastlane-action@v1.2.0
        env:
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          # FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          LANG: ${{ secrets.LANG }}
          LC_ALL: ${{ secrets.LC_ALL }}
          PILOT_APPLE_ID: ${{ secrets.PILOT_APPLE_ID }}
          PILOT_APP_IDENTIFIER: ${{ secrets.PILOT_APP_IDENTIFIER }}
          PILOT_USERNAME: ${{ secrets.PILOT_USERNAME }}
        with:
          # The lane that should be executed.
          lane: beta
          # The relative path from the project root directory to the subdirectory where the fastlane folder is located.
          subdirectory: . # optional
          # The directory where Ruby gems should be installed to and cached. If a relative path is specified, it's applied relative to the location of the Gemfile, which is either the project root or the directory from the `subdirectory` parameter.
          bundle-install-path: . # optional
          # The action tracks usage in Firebase by default. You can disable tracking by setting this parameter to 'true'.
          skip-tracking: true # optional
